language: rust
rust:
  - stable

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran

script:
  - RUSTFLAGS="-C target-cpu=native" cargo test --release
  - cat Cargo.lock
