language: rust
rust:
  - stable

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran

script:
  - cargo install cargo-tree
  - cargo tree
  - cargo test --verbose --all --release
