[package]
name = "wheedle"
version = "0.1.0"
authors = ["Maciej Kula"]

[dependencies]
serde = { version = "1.0.24", features = ["rc"] }
serde_derive = "1.0.24"
serde_json = "1.0"
csv = "1.0.0-beta.5"
bincode = "0.9.2"
rand = { version = "0.5.0-pre.1", features = ["serde1"] }
itertools = "0.7.3"
rayon = "0.9.0"
ndarray = { version = "0.11.0", features = ["blas", "serde-1"] }
blas-src = { version = "0.1.2", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.5.6", default-features = false, features = ["cblas", "static"] }
derive_builder = "0.5.1"
siphasher = "0.2.2"

wyrm = { path = "../wyrm", features = ["fast-math"]}

[dev-dependencies]
criterion = "0.2.3"

[profile.release]
lto = true

[[bench]]
name = "benchmark"
harness = false

[profile.bench]
lto = true
debug = true
