[package]
name = "wheedle"
version = "0.1.0"
authors = ["Maciej Kula"]

[dependencies]
serde = { version = "1.0.24", features = ["rc"] }
serde_derive = "1.0.24"
csv = "1.0.0-beta.5"
bincode = "0.9.2"
rand = "0.4.2"
itertools = "0.7.3"
rayon = "0.9.0"
ndarray = { version = "0.11.0", features = ["blas", "serde-1"] }
blas-src = { version = "0.1.2", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.5.6", default-features = false, features = ["cblas"] }
derive_builder = "0.5.1"
siphasher = "0.2.2"

wyrm = { path = "../wyrm", features = ["fast-math"] }

[profile.release]
lto = true

[profile.bench]
lto = true
debug = true
